stages:

  preprocess_data:
    cmd: python src/data/raw_data_to_npy.py data/raw/train.csv data/raw/test.csv data/processed_data/
    deps:
      - data/raw/train.csv
      - data/raw/test.csv
      - src/data/raw_data_to_npy.py
    outs:
      - data/processed_data/
    
  train_model:
    cmd: python src/train/train.py data/processed_data/x_train.npy data/processed_data/y_train.npy
    deps:
      - data/processed_data/x_train.npy
      - data/processed_data/y_train.npy
      - src/train/train.py
    outs:
      - models/mnist.h5